// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starcatcher.Infrastructure.Data;

#nullable disable

namespace Starcatcher.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241023142219_AllConsortiums")]
    partial class AllConsortiums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.Consortium", b =>
                {
                    b.Property<int>("ConsortiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsortiumId"));

                    b.Property<int>("AdministrationFee")
                        .HasColumnType("int");

                    b.Property<decimal>("AssetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuotaQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ConsortiumId");

                    b.ToTable("Consortia");

                    b.HasData(
                        new
                        {
                            ConsortiumId = 1,
                            AdministrationFee = 15,
                            AssetValue = 35000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para carroaquisição de veículos",
                            QuotaQuantity = 36,
                            Type = 0
                        },
                        new
                        {
                            ConsortiumId = 2,
                            AdministrationFee = 12,
                            AssetValue = 120000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para carroluxo",
                            QuotaQuantity = 48,
                            Type = 1
                        },
                        new
                        {
                            ConsortiumId = 3,
                            AdministrationFee = 10,
                            AssetValue = 12000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para motoaquisição de veículos",
                            QuotaQuantity = 24,
                            Type = 2
                        },
                        new
                        {
                            ConsortiumId = 4,
                            AdministrationFee = 10,
                            AssetValue = 50000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para imoveisresidenciais",
                            QuotaQuantity = 120,
                            Type = 3
                        },
                        new
                        {
                            ConsortiumId = 5,
                            AdministrationFee = 14,
                            AssetValue = 30000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para viagensinternacionais",
                            QuotaQuantity = 24,
                            Type = 4
                        },
                        new
                        {
                            ConsortiumId = 6,
                            AdministrationFee = 10,
                            AssetValue = 15000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para viagensnacionais",
                            QuotaQuantity = 18,
                            Type = 5
                        },
                        new
                        {
                            ConsortiumId = 7,
                            AdministrationFee = 13,
                            AssetValue = 50000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para reformaimóvel",
                            QuotaQuantity = 36,
                            Type = 6
                        },
                        new
                        {
                            ConsortiumId = 8,
                            AdministrationFee = 18,
                            AssetValue = 10000m,
                            CreatedAt = new DateTime(2024, 10, 23, 11, 22, 18, 938, DateTimeKind.Local).AddTicks(4416),
                            Description = "Consórcio para equipamentoseletrônicos",
                            QuotaQuantity = 18,
                            Type = 7
                        });
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.Quota", b =>
                {
                    b.Property<int>("QuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotaId"));

                    b.Property<int>("ConsortiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuotaNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("QuotaId");

                    b.HasIndex("ConsortiumId");

                    b.HasIndex("UserId");

                    b.ToTable("Quotas");
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.Quota", b =>
                {
                    b.HasOne("Starcatcher.Api.Domain.Entities.Consortium", "Consortium")
                        .WithMany("Quotas")
                        .HasForeignKey("ConsortiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Starcatcher.Api.Domain.Entities.User", "User")
                        .WithMany("Quotas")
                        .HasForeignKey("UserId");

                    b.Navigation("Consortium");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Starcatcher.Api.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Starcatcher.Api.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.Consortium", b =>
                {
                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("Starcatcher.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Quotas");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
